ENCODER_MAP_ENABLE = yes
VIA_ENABLE = yes

RGB_MATRIX_DEFAULT_MODE = RGB_MATRIX_SOLID_COLOR
RGB_MATRIX_DEFAULT_HUE = 0
RGB_MATRIX_DEFAULT_SAT = 255
RGB_MATRIX_DEFAULT_VAL = RGB_MATRIX_MAXIMUM_BRIGHTNESS

RGB_MATRIX_HUE_STEP = 4
RGB_MATRIX_SAT_STEP = 8

RGB_MATRIX_SLEEP = yes
